version: "3.8"

services:

  accounts:
    image: mmackowiak/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - mmackowiak-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071

  loans:
    image: mmackowiak/loans:latest
    ports:
      - "8090:8090"
    networks:
      - mmackowiak-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071

  cards:
    image: mmackowiak/cards:latest
    ports:
      - "9000:9000"
    networks:
      - mmackowiak-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071

  configserver:
    image: mmackowiak/config:latest
    ports:
      - "8071:8071"
    networks:
      - mmackowiak-network

networks:
  mmackowiak-network: